# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-01 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('wisher', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('date_granted', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='users.User')),
                ('users_likes', models.ManyToManyField(related_name='liked_wishes', to='users.User')),
            ],
        ),
    ]
