# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-09 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190309_0029'),
        ('wishes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='users_likes',
        ),
        migrations.AddField(
            model_name='wish',
            name='granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wish',
            name='likes',
            field=models.ManyToManyField(related_name='liked', to='users.User'),
        ),
    ]
