# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-03 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0002_auto_20190309_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='date_added',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='date_granted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
