# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-04 00:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0003_auto_20190703_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='date_added',
        ),
    ]
